[package]
name = "stripe-example" # make sure name stays in sync with build.sh
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
ft-sdk = { version = "0.1", path = "../../ft-sdk" }
http = "1"
bytes = "1"
ft-stripe = { version = "0.1", path = "../../ft-stripe" }
